### ISSUE TITLE
Type inference

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/samples-pixi#13]
Hi, 
the following `attachEvent` function casts our ExtendedSprite<CustomData> to Sprite:

```fsharp
let attachEvent (ev: PixiEvent) (handler: EventHandler) (sprite: PIXI.Sprite) =
  sprite.on(!!(string ev), handler) |> ignore
  sprite
```

My question is simple: this function is handy but I would need to get my ExtendedSprite back, not a Sprite. 

So is it better to 

1 - cast back the Sprite to ExtendedSprite with something like that:
```fsharp
    // cast back to ExtendedSprite since attachEvent returns a Sprite
    let backTo (sprite: PIXI.Sprite) = 
      sprite :?> ExtendedSprite<CogData>

    // attach our custom events to enable dragging
    cog
      |> attachEvent Pointerdown (onDragStart cog)
      |> attachEvent Pointerup (onDragEnd cog)
      |> attachEvent Pointermove (onDragMove cog)
      |> backTo
```

2 - or add an attachEvent function which takes and outputs an ExtendedSprite?

Thanks!

**Comment by MangelMaxime** [comment]
In my Helpers, I choose to mimic the class implementation with different modules:

```fs
module Marker =

    let addTo (map: L.Map) (marker: L.Marker) =
        marker.addTo(!^map)
        |> unbox<L.Marker>

    let on (eventType: string) callback (marker: L.Marker) =
        marker.on(eventType, callback)
        |> unbox<L.Marker>

module Polygon =

    let addTo o (polygon : L.Polygon) =
        polygon.addTo o
        |> unbox<L.Polygon>

    let on (eventType, cb) (polygon : L.Polygon) =
        polygon.on(eventType, cb)
        |> unbox<L.Polygon>
```

So yes, that can require more work, but as these are classes from the bindings it's more easier for the User to use the binding in a functional way.

In your case, I think the `backTo` is good enough for the sample usage. Will see if for a bigger app it's works too.

**Comment by whitetigle** [comment]
Thanks for sharing @MangelMaxime I like this way of doing it 👍

**Comment by alfonsogarciacaro** [comment]
@whitetigle To make this more generic and not restrict it to `ExtendedSprite` you can use generic constraints:

```fsharp
let attachEvent<'T when 'T :> PIXI.Sprite> (ev: PixiEvent) (handler: EventHandler) (sprite: 'T) =
  sprite.on(string ev, handler) :?> 'T
```

> I think `sprite.on` returns a self reference so you shouldn't need to return `sprite` explicitly

**Comment by whitetigle** [comment]
Thanks! 👍 I'll try that.
