### ISSUE TITLE
using Func

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/samples-pixi#17]
Hi,
I have updated the **AnimeJS** bindings and I am currently struggling with this: 

```f#
AnimeStatic =
    abstract path: path: U4<string, HTMLElement, SVGElement, obj> * ?percent: float-> Func<string, FunctionBasedValues>
```

FunctionBasedValues being:

```f#
propertyValue =
    U2<float, string>

and FunctionBasedValues =
    Func<Element, float, float, propertyValue>

```

What I would like to do is:

```f#
let path = myInstance.path !!"#motionPath path"

```

and then use it like this:

```f#
let x = path("x")
```

But how could I get the same result with Func?
Thanks!

**Comment by alfonsogarciacaro** [comment]
`ts2fable` is still using `Func` but since Fable 1.x you should be able to use normal F# functions, so you could do:

```fsharp
type propertyValue =
    U2<float, string>

and FunctionBasedValues =
    Element -> float -> float -> propertyValue

and AnimeStatic =
    abstract path: path: obj * ?percent: float-> (string -> FunctionBasedValues)
```

> Note in this signature I'm not using `U4<string, HTMLElement, SVGElement, obj>`. I guess `obj` corresponds to something ts2fable wasn't able to translate but in any case it renders `U4` a bit useless as anything can fit in it. That's why I just replaced it with `obj` :)

With that, you can do:

```fsharp
let path = myInstance.path "#motionPath path"
let x: FunctionBasedValues = path "x"
```

If for some reason you want to keep `Func` you can call it with `.Invoke`:

```fsharp
let x = path.Invoke("x")
```

**Comment by whitetigle** [comment]
Excellent! I updated the bindings consequently. 
Thanks for your help @alfonsogarciacaro 👍
