### ISSUE TITLE
"Safer" project management

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/samples-pixi#23]
Hi, I have been thinking about something

could we change the `whatevever.fsproj `to a standard `app.fsproj` in every project folder.
So we would have an app.fsproj in every project. **(step 1)**

and then update the project json to something like that: 

```
  "particles": {
    "entry": "PixiParticles.fsproj", [etc...]
  },

```

VS (after entry removal)

```
  "particles": {
    [etc...]
  },
```

and then add the entry automatically in the build script under the name `app.fsproj` (**step 2**)? 

So that in the end we wouldn't have to supply a different name for every fsproj file and have the same folder structure for every project. (to go even further in the automation process)

Would that work?

**Comment by MangelMaxime** [comment]
I am OK with this changes. 😊

**Comment by whitetigle** [comment]
While working on new PR addressing this issue, Interestingly I stumbled on this and remember I had the exact same problem a few months ago:

SLN file:
```
Project("{F2A71F9B-5D33-465A-A702-920D77279786}") = "App", "src\tinting\App.fsproj", "{D682EF1E-0BE1-445D-9F32-632B7CE0A8E1}"
EndProject
Project("{F2A71F9B-5D33-465A-A702-920D77279786}") = "App", "src\video\App.fsproj", "{ED8D162E-E396-4BEF-AE32-BB827750C557}"
EndProject
```

Leading to the following error on `dotnet clean`: `error msb5004: the solution-file has two projects name named "src\App"`

**Comment by whitetigle** [comment]
Changing the key from `App` to `App##` works but is clearly not something we want to do I think:

```
Project("{F2A71F9B-5D33-465A-A702-920D77279786}") = "App18", "src\tinting\App.fsproj", "{D682EF1E-0BE1-445D-9F32-632B7CE0A8E1}"
EndProject
Project("{F2A71F9B-5D33-465A-A702-920D77279786}") = "App19", "src\video\App.fsproj", "{ED8D162E-E396-4BEF-AE32-BB827750C557}"
EndProject
```

**Comment by whitetigle** [comment]
Checking the sparse doc on `dotnet sln add` I fail to see how we could add our own key. Any idea?
[Edit] 'Key' being `unique project instance ID`

**Comment by MangelMaxime** [comment]
Ah yes, that's true.

Writing: `App19` isn't something good because if people use VisualStudio then they can't know that App19 is the Video sample.

I think, we will need to let it as it is.

**Comment by MangelMaxime** [comment]
Otherwise, the other solution is to consider the key `particles` to be the same as the folder name.

```json
 "particles": {
    "entry": "PixiParticles.fsproj", [etc...]
  },
```

**Comment by alfonsogarciacaro** [comment]
Yes, if we want to automate the .fsproj name, probably the best idea is to relate it to the ID in project.jso as @MangelMaxime suggests, either using exactly the same ID (`particles.fsproj`) or having a convention for transformation (`particles` -> `PixiParticles.fsproj`). Though probably the first option is the simplest one.

**Comment by whitetigle** [comment]
Done there 😄: [PR#24](https://github.com/fable-compiler/samples-pixi/pull/24)
