### ISSUE TITLE
Samples don't work on Mac with Safari

### ISSUE THREAD

**Issue by davidglassborow** [fable-compiler/samples-pixi#29]
Looking at http://fable.io/samples-pixi/

The samples all work fine on Chrome using a Mac, but nothing shows up on Safari 11.0.2.
No errors shown on the console.  Demos work fine on iOS safari.

I don't think it's a pixi issue, the examples work fine on macOS Safari: http://pixijs.io/examples/#/basics/basic.js

Any ideas what could be causing the problem, anything I can do to help debug the issue ?

**Comment by whitetigle** [comment]
Oh well that's interesting. I haven't done any tests on Safari. 
Could you check how the canvas element is displayed?

![image](https://user-images.githubusercontent.com/883207/34792642-fbabbac0-f648-11e7-8a50-32a10ce68ddf.png)

other idea: is pixi lib loading from the cdn?

**Comment by whitetigle** [comment]
Other question: could you try the samples from the [github repo](https://github.com/fable-compiler/samples-pixi)?

**Comment by whitetigle** [comment]
cc @alfonsogarciacaro could you try as well on Safari on your mac?

**Comment by davidglassborow** [comment]
Ok, checked and the canvas is there, loading fine from the CDN.
All samples seem to have the same problem (I initially found the issue trying to use the fable-pixi template).

I've just checked my laptop, and it works fine on that.  The only difference seems to be the the laptop hasn't had the latest macOS patch (for Spectre), so I wonder if it's something to do with that (reduction in js timers or something).

I'll check on my work computer tomorrow, which is already patched, and see if I can replicate.

**Comment by alfonsogarciacaro** [comment]
I'm on macOS and my computer is already patched, all the samples from fable.io/samples-pixi work for me on Safari (11.0.2) :)

**Comment by whitetigle** [comment]
@davidglassborow Ok thanks! 

@alfonsogarciacaro thanks for checking on your side

**Comment by davidglassborow** [comment]
Ok, works fine on my work machine.  Utterly bizarre, no idea what it could be.

Thanks for your help, and Fable is great !
